server:
  PortServer: :5006
  PprofPort: :5555

mysql:
  MysqlHost:     localhost
  MysqlPort:     3306
  MysqlUser:     root
  MysqlPassword: 1234
  MysqlDbname:   db_upload
  MysqlDriver:   mysql

s3:
  S3Region:
  S3Bucket:
  S3ACL: private