server:
  PortServer: :1234

rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: emails-exchange
  Queue: emails-queue
  RoutingKey: emails-routing-key
  ConsumerTag: emails-consumer
  WorkerPoolSize: 24

redis:
  dns: "localhost:7002"